FROM python:3.12-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:0.11.21 /uv /uvx /bin/

# Set working directory
WORKDIR /code
RUN useradd -m -u 1000 app && chown app:app /code /home/app
USER app

# Dependencies
COPY --chown=app:app pyproject.toml uv.lock /code/
RUN --mount=type=cache,target=/home/app/.cache/uv,uid=1000,gid=1000 \
    uv sync --frozen --no-dev --no-install-project

# Spatial extension installation
RUN uv run python -c "import duckdb; duckdb.connect().execute('INSTALL spatial')"

# The source data cleaning (data_cleaning) scripts (source --> destination)
COPY --chown=app:app ./data_cleaning /code/data_cleaning
COPY --chown=app:app ./run_data_cleaning.py /code/run_data_cleaning.py
COPY --chown=app:app ./build /code/build
COPY --chown=app:app ./api /code/api
COPY --chown=app:app ./logger /code/logger
# TODO: Remove the dependency on app_utils
COPY --chown=app:app ./app_utils /code/app_utils
COPY --chown=app:app ./lake_build.py /code/lake_build.py


ENV DATA_DIR=/data
ENV PYTHONPATH=/code

# Command to run the data cleaning master script
ENTRYPOINT ["uv", "run", "python", "-u", "-m", "run_data_cleaning"]