"""
**Description**:
    Hand-maintained lookup tables and column lists for `clean_parcels.py`.

    The TOWN -> COUNTY dict below (COUNTY_TOWNS) has been hand-verified
    against the canonical GEOID crosswalk in `lake.RAW.vt_town_lines`
    (the same crosswalk `clean_fips.py` builds `vt_town_lines` from):
    every VT town/city/gore/grant in the parcels dataset resolves to the
    correct county with zero mismatches.
"""

geom_cols = ["OBJECTID", "GEOID", "TOWN", "COUNTY", "geometry"]
info_cols = [
    "OBJECTID",
    "GEOID",
    "TOWN",
    "COUNTY",
    "SPAN",
    "PROPTYPE",
    "CAT",
    "CATEGORY",
    "PURPOSE",
    "DESCPROP",
    "RESCODE",
    "ACRESGL",
    "AREAACRESGEOM",
    "CITYGL",
    "STGL",
    "ADDRESS",
    "OWNER1",
    "OWNER2",
    "SOURCENAME",
    "MATCHSTAT",
    "TNAME",
    "INVESTMENTPROP",
    "VACANTLAND",
    "OOSOWNER",
    "EDITOR",
    "EDITDATE",
]
tax_cols = [
    "OBJECTID",
    "GEOID",
    "TOWN",
    "REAL_FLV",
    "HSTED_FLV",
    "NRES_FLV",
    "LAND_LV",
    "IMPRV_LV",
    "EQUIPVAL",
    "EQUIPCODE",
    "INVENVAL",
    "HSDECL",
    "VETEXAMT",
    "EXPDESC",
    "STATUTE",
    "EXEMPT",
    "EXAMT_HS",
    "EXAMT_NR",
    "UVREDUC_HS",
    "UVREDUC_NR",
    "GLVAL_HS",
    "GLVAL_NR",
    "ACREVALUE",
]

STATUTE_MAP = {
    "3848:3849": "Business Inventory & Equipment",
    "3848:38:00": "Business Inventory & Equipment",
    "3840": "Charitable, Fraternal, or Rescue",
    "3840;5405a(a)(4)": "Charitable/Rescue (inc. Education Tax)",
    "3840;54": "Charitable/Rescue (inc. Education Tax)",
    "2741": "Tax Stabilization Contract",
    "24/2741": "Tax Stabilization Contract",
    "3832": "Public, Pious, or Charitable",
    "3832(1)": "Out-of-Town Municipal Property",
    "3832(7)": "Health or Recreational Property",
    "3832(7)(B)": "Non-profit Ice Skating Rink",
    "3832(7B": "Non-profit Ice Skating Rink",
    "5401": "Statewide Education Tax Exception",
    "3752(7)": "Agricultural / Current Use",
}

EXPDESC_MAP = {
    "Statutory": "State Law Exemption",
    "Solar Plant": "Solar Energy Facility",
    "Non-Approved (Voted)": "Local Town-Voted Exemption",
    "Qualified Housing Units": "Affordable / Qualified Housing",
    "Grandfathered": "Pre-existing Historical Exemption",
    "Partial-Statutory": "Partial State Law Exemption",
    "Municipal Contract (Owner Pays)": "Payment in Lieu of Taxes (PILOT)",
    "Ski Lifts / Snow Making Equip": "Ski Resort Equipment",
    "Court Ordered": "Judicially Mandated Exemption",
    "Wind Plant": "Wind Energy Facility",
}

RESCODE_MAP = {
    "T": "TOWN RESIDENT",
    "NS": "OUT OF STATE RESIDENT",
    "S": "VERMONT RESIDENT",
    "C": "CORPORATION/ENTITY",
    "c": "CORPORATION/ENTITY",
}

CAT_MAP = {
    "R1": "Residential I (Under 6 Acres)",
    "R2": "Residential II (6 Acres or More)",
    "M": "Miscellaneous",
    "O": "Other",
    "C": "Commercial",
    "MHL": "Mobile Home Landed (With Land)",
    "S1": "Seasonal I (Under 6 Acres)",
    "MHU": "Mobile Home Unlanded (Without Land)",
    "W": "Woodland",
    "S2": "Seasonal II (6 Acres or More)",
    "F": "Farm",
    "CA": "Commercial Apartments",
    "I": "Industrial",
    "UE": "Utility Electric",
    "UO": "Utility Other",
}

PURPOSE_MAP = {
    "R1": "PRIMARY RESIDENCE",
    "R2": "PRIMARY RESIDENCE",
    "MHL": "PRIMARY RESIDENCE",
    "MHU": "PRIMARY RESIDENCE",
    "S1": "SEASONAL PROPERTY",
    "S2": "SEASONAL PROPERTY",
    "W": "WOODLAND",
    "F": "FARM",
    "CA": "COMMERCIAL APARTMENTS",
    "M": "NOT LISTED",
    "O": "NOT LISTED",
    "C": "COMMERCIAL/INDUSTRIAL/UTILITY",
    "I": "COMMERCIAL/INDUSTRIAL/UTILITY",
    "UE": "COMMERCIAL/INDUSTRIAL/UTILITY",
    "UO": "COMMERCIAL/INDUSTRIAL/UTILITY",
}

EQUIPCODE_MAP = {"E": "ELECTRIC UTILITY", "C": "CABLE UTILITY"}

STATES = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
    "VT",
    "DC",
]

OOS_MAP = {"VERMONT": "VT"}
OOS_MAP.update(
    dict.fromkeys(
        ["QC", "QC CANADA", "PQ", "QUEBEC", "ON", "ONTARIO", "QUE", "BC", "ONT", "CAN"],
        "CANADA",
    )
)
OOS_MAP.update(dict.fromkeys(["MASS", "MA."], "MA"))
OOS_MAP.update(dict.fromkeys(["MICHIGAN"], "MI"))
OOS_MAP.update(dict.fromkeys(["OHIO"], "OH"))
OOS_MAP.update(dict.fromkeys(["CT."], "CT"))
OOS_MAP.update(dict.fromkeys(["R.I."], "RI"))
OOS_MAP.update(dict.fromkeys(["W VA"], "WV"))
OOS_MAP.update(dict.fromkeys(["MARYLAND"], "MD"))
OOS_MAP.update(dict.fromkeys(["N CAROLINA"], "NC"))
OOS_MAP.update(dict.fromkeys(["NEW YORK", "N.Y.", "12513", "N Y"], "NY"))
OOS_MAP.update(dict.fromkeys(["FLORIDA", "FLA"], "FL"))
OOS_MAP.update(
    dict.fromkeys(
        [
            "ENGLAND",
            "AE",
            "UNK",
            "BERMUDA",
            "UK",
            "VY",
            "FRANCE",
            "IND",
            "ARUBA",
            "GERMANY",
            "IRELAND",
            "SWITZERLAN",
            "QLD AUS",
            "LIN",
            "0R",
            "BERLIN",
            "AUSTRALIA",
            "NS",
            "FWI",
            "BAHAMAS",
        ],
        "FOREIGN",
    )
)
OOS_MAP.update(dict.fromkeys(["VI", "PR", "GUAM"], "US TERRITORY"))

# VCGI/Census county assignments for every VT town, city, gore, and grant
# that appears in the parcels TOWN column. Hand-verified against the
# canonical GEOID crosswalk in lake.RAW.vt_town_lines: 0 mismatches.
COUNTY_TOWNS = {
    "ADDISON": [
        "ADDISON",
        "BRIDPORT",
        "BRISTOL",
        "CORNWALL",
        "FERRISBURGH",
        "GOSHEN",
        "GRANVILLE",
        "HANCOCK",
        "LEICESTER",
        "LINCOLN",
        "MIDDLEBURY",
        "MONKTON",
        "NEW HAVEN",
        "ORWELL",
        "PANTON",
        "RIPTON",
        "SALISBURY",
        "SHOREHAM",
        "STARKSBORO",
        "WALTHAM",
        "WEYBRIDGE",
        "WHITING",
        "VERGENNES",
    ],
    "BENNINGTON": [
        "ARLINGTON",
        "BENNINGTON",
        "DORSET",
        "GLASTENBURY",
        "LANDGROVE",
        "MANCHESTER",
        "PERU",
        "POWNAL",
        "READSBORO",
        "RUPERT",
        "SANDGATE",
        "SEARSBURG",
        "SHAFTSBURY",
        "STAMFORD",
        "SUNDERLAND",
        "WINHALL",
        "WOODFORD",
    ],
    "CALEDONIA": [
        "BARNET",
        "BURKE",
        "DANVILLE",
        "GROTON",
        "HARDWICK",
        "KIRBY",
        "LYNDON",
        "NEWARK",
        "PEACHAM",
        "RYEGATE",
        "SAINT JOHNSBURY",
        "SHEFFIELD",
        "STANNARD",
        "SUTTON",
        "WALDEN",
        "WATERFORD",
        "WHEELOCK",
    ],
    "CHITTENDEN": [
        "BOLTON",
        "CHARLOTTE",
        "COLCHESTER",
        "ESSEX",
        "ESSEX JUNCTION",
        "HINESBURG",
        "HUNTINGTON",
        "JERICHO",
        "MILTON",
        "RICHMOND",
        "SAINT GEORGE",
        "SHELBURNE",
        "UNDERHILL",
        "WESTFORD",
        "WILLISTON",
        "BURLINGTON",
        "WINOOSKI",
        "BUELS GORE",
        "SOUTH BURLINGTON",
    ],
    "ESSEX": [
        "AVERILL",
        "BLOOMFIELD",
        "BRIGHTON",
        "BRUNSWICK",
        "CANAAN",
        "CONCORD",
        "EAST HAVEN",
        "FERDINAND",
        "GRANBY",
        "GUILDHALL",
        "LEMINGTON",
        "LEWIS",
        "LUNENBURG",
        "MAIDSTONE",
        "NORTON",
        "VICTORY",
        "AVERYS GORE",
        "WARNERS GRANT",
        "WARREN GORE",
    ],
    "FRANKLIN": [
        "BAKERSFIELD",
        "BERKSHIRE",
        "ENOSBURGH",
        "FAIRFAX",
        "FAIRFIELD",
        "FLETCHER",
        "FRANKLIN",
        "GEORGIA",
        "HIGHGATE",
        "MONTGOMERY",
        "RICHFORD",
        "SAINT ALBANS CITY",
        "SAINT ALBANS TOWN",
        "SHELDON",
        "SWANTON",
    ],
    "GRAND_ISLE": [
        "ALBURGH",
        "GRAND ISLE",
        "ISLE LA MOTTE",
        "NORTH HERO",
        "SOUTH HERO",
    ],
    "LAMOILLE": [
        "BELVIDERE",
        "CAMBRIDGE",
        "EDEN",
        "ELMORE",
        "HYDE PARK",
        "JOHNSON",
        "MORRISTOWN",
        "STOWE",
        "WATERVILLE",
        "WOLCOTT",
    ],
    "ORANGE": [
        "BRADFORD",
        "BRAINTREE",
        "BROOKFIELD",
        "CHELSEA",
        "CORINTH",
        "FAIRLEE",
        "NEWBURY",
        "ORANGE",
        "RANDOLPH",
        "STRAFFORD",
        "THETFORD",
        "TOPSHAM",
        "TUNBRIDGE",
        "VERSHIRE",
        "WASHINGTON",
        "WEST FAIRLEE",
        "WILLIAMSTOWN",
    ],
    "ORLEANS": [
        "ALBANY",
        "BARTON",
        "BROWNINGTON",
        "CHARLESTON",
        "COVENTRY",
        "CRAFTSBURY",
        "DERBY",
        "GLOVER",
        "GREENSBORO",
        "HOLLAND",
        "IRASBURG",
        "JAY",
        "LOWELL",
        "MORGAN",
        "NEWPORT CITY",
        "NEWPORT TOWN",
        "TROY",
        "WESTFIELD",
        "WESTMORE",
    ],
    "RUTLAND": [
        "BENSON",
        "BRANDON",
        "CASTLETON",
        "CHITTENDEN",
        "CLARENDON",
        "DANBY",
        "FAIR HAVEN",
        "HUBBARDTON",
        "IRA",
        "KILLINGTON",
        "MENDON",
        "MIDDLETOWN SPRINGS",
        "MOUNT HOLLY",
        "MOUNT TABOR",
        "PAWLET",
        "PITTSFIELD",
        "PITTSFORD",
        "POULTNEY",
        "PROCTOR",
        "RUTLAND TOWN",
        "RUTLAND CITY",
        "SHREWSBURY",
        "SUDBURY",
        "TINMOUTH",
        "WALLINGFORD",
        "WELLS",
        "WEST HAVEN",
        "WEST RUTLAND",
    ],
    "WASHINGTON": [
        "BARRE TOWN",
        "BERLIN",
        "CABOT",
        "CALAIS",
        "DUXBURY",
        "EAST MONTPELIER",
        "FAYSTON",
        "MARSHFIELD",
        "MIDDLESEX",
        "MORETOWN",
        "NORTHFIELD",
        "PLAINFIELD",
        "ROXBURY",
        "WAITSFIELD",
        "WARREN",
        "WATERBURY",
        "WOODBURY",
        "WORCESTER",
        "BARRE CITY",
        "MONTPELIER",
    ],
    "WINDHAM": [
        "ATHENS",
        "BRATTLEBORO",
        "BROOKLINE",
        "DOVER",
        "DUMMERSTON",
        "GRAFTON",
        "GUILFORD",
        "HALIFAX",
        "JAMAICA",
        "LONDONDERRY",
        "MARLBORO",
        "NEWFANE",
        "PUTNEY",
        "ROCKINGHAM",
        "SOMERSET",
        "STRATTON",
        "TOWNSHEND",
        "VERNON",
        "WARDSBORO",
        "WESTMINSTER",
        "WHITINGHAM",
        "WILMINGTON",
        "WINDHAM",
    ],
    "WINDSOR": [
        "ANDOVER",
        "BALTIMORE",
        "BARNARD",
        "BETHEL",
        "BRIDGEWATER",
        "CAVENDISH",
        "CHESTER",
        "HARTFORD",
        "HARTLAND",
        "LUDLOW",
        "NORWICH",
        "PLYMOUTH",
        "POMFRET",
        "READING",
        "ROCHESTER",
        "ROYALTON",
        "SHARON",
        "SPRINGFIELD",
        "STOCKBRIDGE",
        "WEATHERSFIELD",
        "WEST WINDSOR",
        "WESTON",
        "WINDSOR",
        "WOODSTOCK",
    ],
}

TOWN_COUNTY_MAP = {
    town: county.replace("_", " ").title()
    for county, towns in COUNTY_TOWNS.items()
    for town in towns
}

# Display-cased TOWN, keyed by the raw ALL-CAPS VCGI TOWN value, matching the
# Title Case convention other cleaned datasets (zoning, wastewater) use for
# town names.
TOWN_DISPLAY_MAP = {
    town: town.title() for towns in COUNTY_TOWNS.values() for town in towns
}
