---
title: "Trying runtime sql queries to get cdc geojsons"
author: Fitz Koch
date: today
description:  builds SQL tables from zoning data.
format: 
  html:
    html-math-method: mathjax
    fig-responsive: true
    toc: true
    toc-location: left
    theme: cosmo
    page-layout: full
  ipynb:
    wrap: none
execute: 
  cache: true
editor:
    render-on-save: true
bibliography: /home/fitsl/library/zotero/fjk_library.bib
---

# Setup 

Navigate to root:
```{python}
import sys, os
from pathlib import Path

_project_root = Path.cwd()
while not (_project_root / "api").exists():
    _project_root = _project_root.parent
os.chdir(_project_root)
print(os.getcwd())
```

```{python}
import pandas as pd
import geopandas as gpd
import pyogrio
from pathlib import Path
import duckdb
import re
import geopandas as gpd
from shapely import from_geojson
import xycmap
from matplotlib import pyplot as plt
import seaborn as sns

from app_utils.data_loading import crs_set
```

```{python}
con = duckdb.connect("Data/_Processed/all_data.duckdb", read_only=True)
con.execute("LOAD spatial")
df = con.execute("SELECT * FROM cdc_places").df()
df.head()
```

```{python}
con.execute("SHOW TABLES").df()
```

# Ideas 
There are two cases -- the user wants a single variable, and the user wants two variables. I think we should probably just separate these endpoints rather than make some flexible case, because everything -- the way we show the info, etc., will flow downstream from that. 


```{python}
con.execute("DESCRIBE cdc_places").df()
```

```{python}
single_var_sql = """--sql
    SELECT
        p.LocationID,
        p.Measure,
        p.Data_Value_Type,
        p.Data_Value,
        p.bin,
        c.CountyFIPS,
        ST_ASGEOJSON(c.geom) AS geometry
    FROM cdc_places p
    LEFT JOIN vermont_counties c ON p.LocationID = c.CountyFIPS
"""
```


```{python}
where_string = "WHERE p.Measure IN ('Hearing disability among adults', 'Depression among adults') AND p.Data_Value_Type IN ('Crude prevalence')"
res = con.execute(single_var_sql + where_string).df()
res.head()
```

```{python}
measures = res['Measure'].unique()
m1 = res[res.Measure == measures[0]][['LocationID', 'geometry', 'Data_Value', 'bin']]
m2 = res[res.Measure == measures[1]][['LocationID', 'Data_Value', 'bin']]
wide = m1.merge(m2, on='LocationID', suffixes=('_1', '_2'))
wide
wide.columns
```

```{python}

xcmap = plt.cm.viridis_r
ycmap = plt.cm.Blues
n = (3, 3)  # x, y
cmap = xycmap.mean_xycmap(xcmap=xcmap, ycmap=ycmap, n=n)
plt.imshow(cmap, origin='lower')
```

```{python}
def to_rgba(r):
    if pd.isna(r["bin_1"]) or pd.isna(r["bin_2"]):
        return [0, 0, 0, 0]  # transparent for missing
    rgba = cmap[int(r["bin_2"]), int(r["bin_1"])]
    return [round(c * 255) for c in rgba]


wide["color"] = wide.apply(to_rgba, axis=1)
wide.head()
```


Lets take a quick look at how that actually looks...

```{python}
gdf = gpd.GeoDataFrame(wide, geometry=wide["geometry"].apply(from_geojson))
gdf.plot(color=gdf["color"].apply(lambda c: [v/255 for v in c]))  
```

Not exactly stunning, but this should do okay on the front end. Fine tuning the colormap is something we can do later. 

# Scatter plot, by bin color 
To look at the sections with a little more detail: 


```{python}
gdf["sns_color"] = gdf["color"].apply(lambda x: tuple([a/255 for a in x]))
gdf["sns_color"]
gdf["LocationID"].unique()
```

```{python}
plt.scatter(gdf["Data_Value_1"], gdf["Data_Value_2"], c=gdf["sns_color"].tolist())
```

Doesn't look super fancy, but will be better when there are more data points.


# Clustering Features

```{python}
sme_places = con.execute("""--sql
    SELECT 
        LocationID, 
        Measure, Data_Value, 
        Data_Value_Type
    FROM cdc_places
    WHERE Data_Value_Type IN ('Crude prevalence') 
            AND SME_Highlight = 1
""").df()
# places.head()
pv = sme_places.pivot(columns="Measure", values="Data_Value", index="LocationID")
```

## Cluster Plot and Dendogram

```{python}
sns.clustermap(pv.corr())
```

### Flat Clusters
```{python}
from scipy.cluster.hierarchy import linkage, fcluster
from scipy.spatial.distance import squareform

corr = pv.corr()
dist = 1 - corr.abs()  # co-movement distance, sets diag to zero
Z = linkage(squareform(dist), method="average")

labels = fcluster(Z, t=0.5, criterion="distance")  # k=4 groups
groups = pd.Series(labels, index=corr.index).sort_values()
print(groups)
```

## Parallel Lines Plot
```{python}
pvi = (pv - pv.mean()) / pv.std() # standardize cols to standard deviation
pvi = pvi.reset_index()
```

```{python}
pd.plotting.parallel_coordinates(frame=pvi, class_column="LocationID")
plt.xticks(rotation=90)
plt.show()
```

Can also compare just two counties...

```{python}
fips = ["50007", "50001"]
pvi_lim = pvi[pvi["LocationID"].isin(fips)]

pd.plotting.parallel_coordinates(frame=pvi_lim, class_column="LocationID")
plt.xticks(rotation=90)
plt.show()
```

## PCA 
```{python}
from sklearn.decomposition import PCA
X = pvi.set_index("LocationID")
pca = PCA(n_components=2)
scores = pca.fit_transform(X)
print(pca.explained_variance_ratio_)
```

```{python}
pvi["pca1"] = scores[:, 0] 
pvi.head()
```

```{python}
pca.components_[0]
``` 

Look at how each column contributes to the PCA...: 
```{python}
cols = [col for col in pvi.columns if col not in ["LocationID", "pca1"]]
for col, weight in zip(cols, pca.components_[0]):
    print(f"{col}, {weight:.03f}")
```

Generally, positive = bad, negative = good, thouh we see that some tests -- routine checkup, cancer screening -- are not.  Depression is mostly noise; binge drinking correlates presumably to wealthy 

## PCA with national spread


Note that the above is all about the variance in *standardized Vermont*, not all of it. So now we'll do that... 

```{python}
sme_indicators = df["Measure"].where(df["SME_Highlight"]==True).unique().tolist()
indicators_sql = ", ".join(f"'{i}'" for i in sme_indicators)
```


```{python}
db = duckdb.connect()

data_dir = Path("Data")
path = data_dir / "CDC" / "CDC_Places.csv"

db.execute(f"""--sql
  CREATE OR REPLACE VIEW places_raw AS 
  SELECT * FROM read_csv('{path}')
""")

db.execute(f"""--sql
  CREATE OR REPLACE VIEW cdc_places_temp AS 
  SELECT * EXCLUDE (Geolocation,  StateDesc),
      CASE WHEN 
        DataValueTypeID = 'CrdPrv' AND Measure IN ({indicators_sql})
        THEN 1 else 0 END 
     AS SME_Highlight
  FROM places_raw
    WHERE Data_Value_Type IN ('Crude prevalence') 
        AND SME_Highlight = 1
  """)

us_df = db.execute(f"""--sql
  SELECT * FROM cdc_places_temp
""").df()
```


```{python}
us_df.head()
```

Pivot
```{python}
pv_us = us_df.pivot(columns="Measure", values="Data_Value", index="LocationID")
pv_us = pv_us.dropna(axis=0, how="any")
pv_us.head()
```

Standardize
```{python}
pvi_us = (pv_us - pv_us.mean()) / pv_us.std() # standardize cols to standard deviation
pvi_us = pvi_us.reset_index()
pvi_us.head()
```


```{python}
from sklearn.decomposition import PCA
X = pvi_us.set_index("LocationID")
pca_us = PCA(n_components=2)
scores_us = pca_us.fit_transform(X)
print(pca_us.explained_variance_ratio_)
```

```{python}
pvi_us["pca1"] = scores_us[:, 0] 
pvi_us.head()
```

```{python}
pca_us.components_[0]
``` 

Look at how each column contributes to the PCA...: 
```{python}
cols = [col for col in pvi_us.columns if col not in ["LocationID", "pca1"]]
for col, weight_vt, weight_us in zip(cols, pca.components_[0], pca_us.components_[0]):
    print(f"{col}, {weight_vt:.03f} {weight_us:.03f}")
```

This is good; the results are quite similar. So we can use the national loadings and not worry about them too much.


```{python}
scores_vtus = pca_us.transform(pvi.set_index("LocationID")[cols])
pvi["pca_us_vt"] = scores_vtus[:, 0]
pvi.head()
```

```{python}
fips_mapper = {
    50001: "Addison",
    50003: "Bennington",
    50005: "Caledonia",
    50007: "Chittenden",
    50009: "Essex",
    50011: "Franklin",
    50013: "Grand Isle",
    50015: "Lamoille",
    50017: "Orange",
    50019: "Orleans",
    50021: "Rutland",
    50023: "Washington",
    50025: "Windham",
    50027: "Windsor"
}

pvi["LocationID"] = pvi["LocationID"].astype(int)
pvi["Location"] = pvi["LocationID"].map(fips_mapper)
pvi.head()
```

```{python}
sns.barplot(data=pvi, x="Location", y="pca_us_vt")
plt.xticks(rotation=90)
```