"""
**Author**:
    Fitz Koch
**Created**:
    2026-06-01
**Updated**:
    2026-09-01
**Description**:
    Provides a lazy connection to the finalized database,
    `warehouse.duckdb`, which is derived from the CLEANED DuckLake tables.
"""

import logging
import os
from pathlib import Path

import duckdb

logger = logging.getLogger(__name__)

BACKEND_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = Path(os.environ.get("DATA_DIR", BACKEND_DIR / "Data"))
WAREHOUSE_PATH = DATA_DIR / "warehouse.duckdb"


def _load_spatial(con: duckdb.DuckDBPyConnection) -> None:
    """Load the spatial extension."""
    try:
        con.execute("LOAD spatial")
    except duckdb.Error as e:
        raise RuntimeError("The DuckDB spatial extension could not be loaded.") from e


class _ThreadSafeDB:
    """Wraps one connection; each execute() gets its own cursor.

    A single DuckDB connection is not safe across FastAPI's threadpool:
    concurrent execute()/.df() calls steal each other's results (.df()
    returns None). Cursors share the database but not result state.
    """

    def __init__(self, con: duckdb.DuckDBPyConnection):
        self._con = con

    def execute(self, *args, **kwargs):
        return self._con.cursor().execute(*args, **kwargs)

    def __getattr__(self, name):
        return getattr(self._con, name)


def get_db() -> _ThreadSafeDB:
    """
    Open a read-only connection to the production warehouse.

    The warehouse is generated by the ETL process. If it does not exist,
    run `just etl` before starting the API.
    """
    if not WAREHOUSE_PATH.exists():
        raise RuntimeError(
            f"Production database not found at {WAREHOUSE_PATH}.\n"
            "Run `just etl` first to build the production database."
        )

    try:
        con = duckdb.connect(WAREHOUSE_PATH, read_only=True)
        _load_spatial(con)
        return _ThreadSafeDB(con)

    except Exception as e:
        raise RuntimeError(
            f"Could not open the production database at {WAREHOUSE_PATH}.\n"
            "Try running `just run-etl` to rebuild the production database."
        ) from e
