"""
**Author**:
    Fitz Koch
**Created**:
    2026-06-01
**Updated**:
    2026-09-01
**Description**:
    Provides a lazy connection to the finalized database,
    `warehouse.duckdb`, which is derived from the CLEANED DuckLake tables.
"""

import logging
import os
from pathlib import Path

import duckdb

logger = logging.getLogger(__name__)

BACKEND_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = Path(os.environ.get("DATA_DIR", BACKEND_DIR / "Data"))
WAREHOUSE_PATH = DATA_DIR / "warehouse.duckdb"


def _load_spatial(con: duckdb.DuckDBPyConnection) -> None:
    """Load the spatial extension."""
    try:
        con.execute("LOAD spatial")
    except duckdb.Error as exc:
        raise RuntimeError("The DuckDB spatial extension could not be loaded.") from exc


def get_db() -> duckdb.DuckDBPyConnection:
    """
    Open a read-only connection to the production warehouse.

    The warehouse is generated by the ETL process. If it does not exist,
    run `just etl` before starting the API.
    """
    if not WAREHOUSE_PATH.exists():
        raise RuntimeError(
            f"Production database not found at {WAREHOUSE_PATH}.\n"
            "Run `just etl` first to build the production database."
        )

    try:
        con = duckdb.connect(WAREHOUSE_PATH, read_only=True)
        _load_spatial(con)
        return con

    except Exception as exc:
        raise RuntimeError(
            f"Could not open the production database at {WAREHOUSE_PATH}.\n"
            "Try running `just etl` to rebuild the production database."
        ) from exc
