name: Vermont Data Collaborative ETL

on:
  schedule:
    # Runs once a month on the 30th day (@2:00 AM)
    - cron: '0 2 30 * *'
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: '0.11.21'
        enable-cache: true
    
    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
        podman --version

    - name: Install Just and DuckDB
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems | bash -s -- --to /usr/local/bin
        wget https://github.com

    - name: Run ETL Pipeline
      # Grab data just from the latest year to add to the database (2024)
      run: just run-etl 2024 2024

    - name: Commit and Push Updated DuckDB Database
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add backend/Data/warehouse.duckdb
        git diff-index --quiet HEAD || git commit -m "Automated ETL: Update DuckDB data [skip ci]"
        git push